# Generated by Django 2.1.5 on 2019-09-09 16:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0002_auto_20190909_1203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
