# Generated by Django 2.1.5 on 2019-09-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0003_auto_20190909_1611'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
    ]
