# Generated by Django 2.1.5 on 2019-09-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0007_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
