# Generated by Django 2.1.5 on 2019-09-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0008_orderitem_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
