# Generated by Django 2.1.5 on 2019-09-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0009_auto_20190911_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
