# Generated by Django 2.1.5 on 2019-09-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders2', '0010_auto_20190917_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
